-- HR AI Agent — Supabase Database Schema (Integer ID Version)
-- Version: 2.0 (ใช้ BIGINT Auto-Increment แทน UUID เพื่อความเข้าใจง่าย)

-- ==========================================
-- ล้างตารางเดิม (ถ้ามี) ก่อนสร้างใหม่
-- ==========================================
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS workflow_events CASCADE;
DROP TABLE IF EXISTS ai_recommendations CASCADE;
DROP TABLE IF EXISTS ai_runs CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS hires CASCADE;
DROP TABLE IF EXISTS offers CASCADE;
DROP TABLE IF EXISTS dl_test_results CASCADE;
DROP TABLE IF EXISTS dl_tests CASCADE;
DROP TABLE IF EXISTS interview_feedback CASCADE;
DROP TABLE IF EXISTS interview_interviewers CASCADE;
DROP TABLE IF EXISTS interviews CASCADE;
DROP TABLE IF EXISTS applications CASCADE;
DROP TABLE IF EXISTS candidate_documents CASCADE;
DROP TABLE IF EXISTS candidates CASCADE;
DROP TABLE IF EXISTS job_descriptions CASCADE;
DROP TABLE IF EXISTS vacancies CASCADE;
DROP TABLE IF EXISTS position_requirements CASCADE;
DROP TABLE IF EXISTS positions CASCADE;
DROP TABLE IF EXISTS resignations CASCADE;
DROP TABLE IF EXISTS employees CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;

-- ==========================================
-- 1. Users & Roles
-- ==========================================

CREATE TABLE roles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(50) NOT NULL UNIQUE, -- HR_ADMIN, HIRING_MANAGER, INTERVIEWER, CANDIDATE
  description TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  name VARCHAR(255) NOT NULL,
  name_th VARCHAR(255),
  role_id BIGINT REFERENCES roles(id),
  department VARCHAR(100),
  avatar_url TEXT,
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 2. Employees & Resignations
-- ==========================================

CREATE TABLE employees (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  employee_code VARCHAR(20) UNIQUE NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  first_name_th VARCHAR(100),
  last_name_th VARCHAR(100),
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(20),
  department VARCHAR(100),
  position VARCHAR(200),
  level VARCHAR(50),
  hire_date DATE NOT NULL,
  status VARCHAR(20) DEFAULT 'ACTIVE', -- ACTIVE, RESIGNED, TERMINATED
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE resignations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id BIGINT REFERENCES employees(id) NOT NULL,
  resignation_date DATE NOT NULL,
  last_working_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED, COMPLETED
  approved_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. Positions & Requirements
-- ==========================================

CREATE TABLE positions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(200) NOT NULL,
  title_th VARCHAR(200),
  department VARCHAR(100) NOT NULL,
  department_th VARCHAR(100),
  level VARCHAR(50),
  report_to VARCHAR(200),
  responsibilities JSONB DEFAULT '[]',
  responsibilities_th JSONB DEFAULT '[]',
  qualifications JSONB DEFAULT '[]',
  qualifications_th JSONB DEFAULT '[]',
  is_active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE position_requirements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id BIGINT REFERENCES positions(id) NOT NULL,
  requirement_type VARCHAR(50) NOT NULL, -- EDUCATION, EXPERIENCE, SKILL, CERTIFICATION, LANGUAGE
  requirement_key VARCHAR(100) NOT NULL,
  requirement_value TEXT NOT NULL,
  is_required BOOLEAN DEFAULT TRUE,
  weight INTEGER DEFAULT 1,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 4. Vacancies & Job Descriptions
-- ==========================================

CREATE TABLE vacancies (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id BIGINT REFERENCES positions(id) NOT NULL,
  state VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    -- DRAFT, JD_GENERATING, WAITING_HR_APPROVAL, APPROVED,
    -- PUBLISHED, RECRUITING, INTERVIEWING, OFFERING, FILLED, CLOSED
  priority VARCHAR(10) DEFAULT 'MEDIUM', -- LOW, MEDIUM, HIGH, URGENT
  headcount INTEGER DEFAULT 1,
  filled INTEGER DEFAULT 0,
  open_date DATE,
  close_date DATE,
  reason VARCHAR(20), -- NEW_POSITION, REPLACEMENT, EXPANSION
  reason_detail TEXT,
  hiring_manager_id BIGINT REFERENCES users(id),
  created_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE job_descriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vacancy_id BIGINT REFERENCES vacancies(id) NOT NULL,
  version INTEGER DEFAULT 1,
  job_title VARCHAR(200) NOT NULL,
  job_title_th VARCHAR(200),
  summary TEXT,
  summary_th TEXT,
  responsibilities JSONB DEFAULT '[]',
  responsibilities_th JSONB DEFAULT '[]',
  requirements JSONB DEFAULT '[]',
  requirements_th JSONB DEFAULT '[]',
  preferred_skills JSONB DEFAULT '[]',
  education JSONB DEFAULT '[]',
  experience JSONB DEFAULT '[]',
  benefits JSONB DEFAULT '[]',
  benefits_th JSONB DEFAULT '[]',
  salary_min NUMERIC(12,2),
  salary_max NUMERIC(12,2),
  salary_currency VARCHAR(3) DEFAULT 'THB',
  generated_by_ai BOOLEAN DEFAULT FALSE,
  ai_model_version VARCHAR(50),
  ai_confidence NUMERIC(3,2),
  approved_by BIGINT REFERENCES users(id),
  approved_at TIMESTAMPTZ,
  is_current BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 5. Candidates & Documents
-- ==========================================

CREATE TABLE candidates (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  first_name_th VARCHAR(100),
  last_name_th VARCHAR(100),
  email VARCHAR(255) NOT NULL UNIQUE,
  phone VARCHAR(20),
  avatar_url TEXT,
  current_position VARCHAR(200),
  current_company VARCHAR(200),
  experience_years NUMERIC(3,1) DEFAULT 0,
  education JSONB DEFAULT '[]',
  skills JSONB DEFAULT '[]',
  languages JSONB DEFAULT '[]',
  source VARCHAR(30), -- CAREER_PORTAL, EMAIL, CANDIDATE_POOL, REFERRAL, LINKEDIN
  resume_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE candidate_documents (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  document_type VARCHAR(50) NOT NULL, -- RESUME, PORTFOLIO, CERTIFICATE, TRANSCRIPT, OTHER
  file_name VARCHAR(255) NOT NULL,
  file_url TEXT NOT NULL,
  file_size INTEGER,
  mime_type VARCHAR(100),
  uploaded_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 6. Applications (Candidate + Vacancy)
-- ==========================================

CREATE TABLE applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  vacancy_id BIGINT REFERENCES vacancies(id) NOT NULL,
  state VARCHAR(30) NOT NULL DEFAULT 'APPLIED',
  match_score NUMERIC(5,2),
  hr_notes TEXT,
  rejection_reason TEXT,
  applied_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(candidate_id, vacancy_id)
);

-- ==========================================
-- 7. Interviews & Feedback
-- ==========================================

CREATE TABLE interviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES applications(id) NOT NULL,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  vacancy_id BIGINT REFERENCES vacancies(id) NOT NULL,
  interview_type VARCHAR(20) NOT NULL, -- PHONE_SCREEN, TECHNICAL, BEHAVIORAL, PANEL, FINAL
  status VARCHAR(20) DEFAULT 'SCHEDULED', -- SCHEDULED, CONFIRMED, IN_PROGRESS, COMPLETED, CANCELLED, NO_SHOW
  scheduled_at TIMESTAMPTZ NOT NULL,
  duration INTEGER DEFAULT 60,
  location TEXT,
  meeting_url TEXT,
  overall_score NUMERIC(5,2),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE interview_interviewers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) NOT NULL,
  user_id BIGINT REFERENCES users(id) NOT NULL,
  UNIQUE(interview_id, user_id)
);

CREATE TABLE interview_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  interview_id BIGINT REFERENCES interviews(id) NOT NULL,
  interviewer_id BIGINT REFERENCES users(id) NOT NULL,
  scores JSONB NOT NULL DEFAULT '{}',
  overall_score NUMERIC(5,2),
  strengths JSONB DEFAULT '[]',
  concerns JSONB DEFAULT '[]',
  recommendation VARCHAR(20), -- STRONG_HIRE, HIRE, HOLD, NO_HIRE
  notes TEXT,
  submitted_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(interview_id, interviewer_id)
);

-- ==========================================
-- 8. DL Tests & Results
-- ==========================================

CREATE TABLE dl_tests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES applications(id) NOT NULL,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  external_test_id VARCHAR(255),
  test_url TEXT,
  status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED, EXPIRED
  assigned_at TIMESTAMPTZ DEFAULT NOW(),
  expires_at TIMESTAMPTZ
);

CREATE TABLE dl_test_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dl_test_id BIGINT REFERENCES dl_tests(id) NOT NULL,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  application_id BIGINT REFERENCES applications(id) NOT NULL,
  knowledge_score NUMERIC(5,2),
  practical_score NUMERIC(5,2),
  ai_literacy_score NUMERIC(5,2),
  total_score NUMERIC(5,2),
  max_score NUMERIC(5,2) DEFAULT 100,
  result_status VARCHAR(10), -- PASS, FAIL
  details JSONB DEFAULT '{}',
  completed_at TIMESTAMPTZ,
  received_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 9. Offers & Hires
-- ==========================================

CREATE TABLE offers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id BIGINT REFERENCES applications(id) NOT NULL,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  vacancy_id BIGINT REFERENCES vacancies(id) NOT NULL,
  offered_salary NUMERIC(12,2),
  salary_currency VARCHAR(3) DEFAULT 'THB',
  start_date DATE,
  benefits JSONB DEFAULT '[]',
  status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, ACCEPTED, REJECTED, EXPIRED
  offered_at TIMESTAMPTZ DEFAULT NOW(),
  responded_at TIMESTAMPTZ,
  created_by BIGINT REFERENCES users(id)
);

CREATE TABLE hires (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  offer_id BIGINT REFERENCES offers(id) NOT NULL,
  candidate_id BIGINT REFERENCES candidates(id) NOT NULL,
  employee_id BIGINT REFERENCES employees(id),
  start_date DATE NOT NULL,
  onboarding_status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, IN_PROGRESS, COMPLETED
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 10. Notifications
-- ==========================================

CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) NOT NULL,
  title VARCHAR(255) NOT NULL,
  title_th VARCHAR(255),
  message TEXT NOT NULL,
  message_th TEXT,
  type VARCHAR(20) DEFAULT 'INFO', -- INFO, SUCCESS, WARNING, ACTION_REQUIRED
  is_read BOOLEAN DEFAULT FALSE,
  action_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 11. AI Runs & Recommendations
-- ==========================================

CREATE TABLE ai_runs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  agent_type VARCHAR(50) NOT NULL, -- JD_GENERATOR, CANDIDATE_MATCHER, RECRUITMENT_RECOMMENDER, RESUME_PARSER
  status VARCHAR(20) DEFAULT 'RUNNING',
  input JSONB DEFAULT '{}',
  output JSONB DEFAULT '{}',
  model_version VARCHAR(50),
  prompt_version VARCHAR(50),
  started_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  duration_ms INTEGER,
  error_message TEXT
);

CREATE TABLE ai_recommendations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ai_run_id BIGINT REFERENCES ai_runs(id),
  application_id BIGINT REFERENCES applications(id),
  candidate_id BIGINT REFERENCES candidates(id),
  vacancy_id BIGINT REFERENCES vacancies(id),
  recommendation_type VARCHAR(50) NOT NULL,
  match_score NUMERIC(5,2),
  confidence NUMERIC(3,2),
  required_criteria JSONB DEFAULT '{}',
  strengths JSONB DEFAULT '[]',
  strengths_th JSONB DEFAULT '[]',
  gaps JSONB DEFAULT '[]',
  gaps_th JSONB DEFAULT '[]',
  recommendation VARCHAR(20),
  reasoning TEXT,
  reasoning_th TEXT,
  scores JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 12. Workflow Events & Audit Logs
-- ==========================================

CREATE TABLE workflow_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_type VARCHAR(100) NOT NULL,
  entity_type VARCHAR(30) NOT NULL,
  entity_id BIGINT NOT NULL,
  actor_type VARCHAR(20) NOT NULL, -- HR, AI_AGENT, AUTOMATION, CANDIDATE, SYSTEM
  actor_id VARCHAR(100) NOT NULL,
  actor_name VARCHAR(255),
  description TEXT,
  description_th TEXT,
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id),
  user_name VARCHAR(255),
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(50) NOT NULL,
  entity_id BIGINT,
  details TEXT,
  old_values JSONB,
  new_values JSONB,
  ip_address INET,
  user_agent TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- Indexes for performance
-- ==========================================

CREATE INDEX idx_applications_candidate ON applications(candidate_id);
CREATE INDEX idx_applications_vacancy ON applications(vacancy_id);
CREATE INDEX idx_applications_state ON applications(state);
CREATE INDEX idx_vacancies_state ON vacancies(state);
CREATE INDEX idx_interviews_application ON interviews(application_id);
CREATE INDEX idx_interviews_scheduled ON interviews(scheduled_at);
CREATE INDEX idx_workflow_events_entity ON workflow_events(entity_type, entity_id);
CREATE INDEX idx_workflow_events_created ON workflow_events(created_at DESC);
CREATE INDEX idx_audit_logs_user ON audit_logs(user_id);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at DESC);
CREATE INDEX idx_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX idx_ai_recommendations_application ON ai_recommendations(application_id);
