// Mock Data — AI Responses, Workflow Events, Notifications

import type { AIRecruitmentRecommendation, WorkflowEvent } from '@/lib/types/ai';
import type { Notification, User } from '@/lib/types';

export const mockAIRecommendations: AIRecruitmentRecommendation[] = [
  {
    id: 'rec-001',
    applicationId: 'app-001',
    candidateName: 'Thanaporn Kittisak',
    vacancyTitle: 'Digital Marketing Manager',
    overallFit: 84,
    scores: {
      jobMatch: 88,
      experience: 90,
      dlTest: 76,
      interview: 82,
    },
    strengths: [
      'Direct digital marketing experience of 6 years',
      'Has CRM + Analytics expertise',
      'Strong leadership demonstrated in current role',
    ],
    strengthsTh: [
      'ประสบการณ์ตรงด้านการตลาดดิจิทัล 6 ปี',
      'มีความเชี่ยวชาญ CRM + Analytics',
      'แสดงความเป็นผู้นำที่แข็งแกร่งในตำแหน่งปัจจุบัน',
    ],
    gaps: [
      'DL Practical score below benchmark (76 vs 80)',
      'No higher education sector experience',
    ],
    gapsTh: [
      'คะแนน DL Practical ต่ำกว่า Benchmark (76 vs 80)',
      'ไม่มีประสบการณ์ในภาคการศึกษา',
    ],
    recommendation: 'HIRE',
    reasoning: 'Strong overall fit with minor gaps in DL test. Experience and interview performance compensate for DL shortfall. Recommend proceeding with offer.',
    reasoningTh: 'เหมาะสมโดยรวมดี มีจุดอ่อนเล็กน้อยใน DL Test ประสบการณ์และผลสัมภาษณ์ชดเชยส่วนที่ขาด แนะนำเสนอตำแหน่ง',
    generatedAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'rec-002',
    applicationId: 'app-002',
    candidateName: 'Pirasak Wongcharoen',
    vacancyTitle: 'Senior Software Engineer',
    overallFit: 91,
    scores: {
      jobMatch: 92,
      experience: 95,
      dlTest: 0,
      interview: 0,
    },
    strengths: [
      'Exceptional technical background from Agoda',
      'Master\'s in CS with high GPA',
      'Full-stack proficiency matches role perfectly',
    ],
    strengthsTh: [
      'พื้นฐานเทคนิคยอดเยี่ยมจาก Agoda',
      'ปริญญาโท CS เกรดสูง',
      'ทักษะ Full-stack ตรงกับตำแหน่งอย่างสมบูรณ์',
    ],
    gaps: [],
    gapsTh: [],
    recommendation: 'STRONG_HIRE',
    reasoning: 'Top candidate with near-perfect job match. Awaiting interview and DL test, but profile strongly suggests high potential.',
    reasoningTh: 'ผู้สมัครอันดับต้น คะแนนจับคู่เกือบสมบูรณ์แบบ รอผลสัมภาษณ์และ DL Test แต่โปรไฟล์บ่งชี้ศักยภาพสูง',
    generatedAt: '2026-08-14T10:00:00Z',
  },
];

export const mockWorkflowEvents: WorkflowEvent[] = [
  {
    id: 'evt-001',
    type: 'VACANCY_CREATED',
    entityType: 'VACANCY',
    entityId: 'vac-001',
    actorType: 'HR',
    actorId: 'user-001',
    actorName: 'Wanida Kulrat',
    description: 'Created vacancy for Digital Marketing Manager',
    descriptionTh: 'สร้างตำแหน่งว่าง ผู้จัดการฝ่ายการตลาดดิจิทัล',
    createdAt: '2026-08-01T09:00:00Z',
  },
  {
    id: 'evt-002',
    type: 'JD_GENERATED',
    entityType: 'VACANCY',
    entityId: 'vac-001',
    actorType: 'AI_AGENT',
    actorId: 'ai-jd-agent',
    actorName: 'JD Agent',
    description: 'AI generated job description for Digital Marketing Manager',
    descriptionTh: 'AI สร้าง Job Description สำหรับผู้จัดการฝ่ายการตลาดดิจิทัล',
    createdAt: '2026-08-02T10:00:00Z',
  },
  {
    id: 'evt-003',
    type: 'JD_APPROVED',
    entityType: 'VACANCY',
    entityId: 'vac-001',
    actorType: 'HR',
    actorId: 'user-001',
    actorName: 'Wanida Kulrat',
    description: 'Approved job description (v2)',
    descriptionTh: 'อนุมัติ Job Description (v2)',
    createdAt: '2026-08-05T14:30:00Z',
  },
  {
    id: 'evt-004',
    type: 'VACANCY_PUBLISHED',
    entityType: 'VACANCY',
    entityId: 'vac-001',
    actorType: 'AUTOMATION',
    actorId: 'system',
    actorName: 'System',
    description: 'Vacancy published to career portal and email channels',
    descriptionTh: 'เผยแพร่ตำแหน่งไปยัง Career Portal และช่องทางอีเมล',
    createdAt: '2026-08-05T15:00:00Z',
  },
  {
    id: 'evt-005',
    type: 'CANDIDATE_APPLIED',
    entityType: 'APPLICATION',
    entityId: 'app-001',
    actorType: 'CANDIDATE',
    actorId: 'cand-001',
    actorName: 'Thanaporn Kittisak',
    description: 'Candidate applied for Digital Marketing Manager',
    descriptionTh: 'ผู้สมัครสมัครตำแหน่งผู้จัดการฝ่ายการตลาดดิจิทัล',
    createdAt: '2026-08-06T10:00:00Z',
  },
  {
    id: 'evt-006',
    type: 'AI_SCREENING_COMPLETED',
    entityType: 'APPLICATION',
    entityId: 'app-001',
    actorType: 'AI_AGENT',
    actorId: 'ai-screening-agent',
    actorName: 'Screening Agent',
    description: 'AI screening completed — Match Score: 88% — Recommendation: SHORTLIST',
    descriptionTh: 'AI คัดกรองเสร็จ — คะแนนจับคู่: 88% — แนะนำ: คัดเลือก',
    createdAt: '2026-08-06T10:30:00Z',
  },
  {
    id: 'evt-007',
    type: 'CANDIDATE_SHORTLISTED',
    entityType: 'APPLICATION',
    entityId: 'app-001',
    actorType: 'HR',
    actorId: 'user-001',
    actorName: 'Wanida Kulrat',
    description: 'HR shortlisted candidate Thanaporn Kittisak',
    descriptionTh: 'HR คัดเลือกผู้สมัคร ธนพร กิตติศักดิ์',
    createdAt: '2026-08-07T09:00:00Z',
  },
  {
    id: 'evt-008',
    type: 'INTERVIEW_SCHEDULED',
    entityType: 'INTERVIEW',
    entityId: 'int-001',
    actorType: 'HR',
    actorId: 'user-001',
    actorName: 'Wanida Kulrat',
    description: 'Panel interview scheduled for Aug 14, 2026',
    descriptionTh: 'นัดสัมภาษณ์คณะกรรมการ 14 ส.ค. 2569',
    createdAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'evt-009',
    type: 'DL_TEST_COMPLETED',
    entityType: 'APPLICATION',
    entityId: 'app-001',
    actorType: 'CANDIDATE',
    actorId: 'cand-001',
    actorName: 'Thanaporn Kittisak',
    description: 'DL Test completed — Total Score: 82/100 — PASS',
    descriptionTh: 'ทำ DL Test เสร็จ — คะแนนรวม: 82/100 — ผ่าน',
    createdAt: '2026-08-12T15:30:00Z',
  },
  {
    id: 'evt-010',
    type: 'INTERVIEW_COMPLETED',
    entityType: 'INTERVIEW',
    entityId: 'int-001',
    actorType: 'HR',
    actorId: 'user-002',
    actorName: 'Somchai Prasert',
    description: 'Panel interview completed — Overall Score: 86/100',
    descriptionTh: 'สัมภาษณ์คณะกรรมการเสร็จ — คะแนนรวม: 86/100',
    createdAt: '2026-08-14T12:00:00Z',
  },
  {
    id: 'evt-011',
    type: 'AI_RECOMMENDATION_GENERATED',
    entityType: 'APPLICATION',
    entityId: 'app-001',
    actorType: 'AI_AGENT',
    actorId: 'ai-recruitment-agent',
    actorName: 'Recruitment Agent',
    description: 'AI recommendation generated — Overall Fit: 84% — Recommend: HIRE',
    descriptionTh: 'AI สร้างคำแนะนำ — ความเหมาะสมรวม: 84% — แนะนำ: จ้างงาน',
    createdAt: '2026-08-15T16:00:00Z',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'notif-001',
    userId: 'user-001',
    title: 'New Application',
    titleTh: 'ใบสมัครใหม่',
    message: 'Kittipat Leesuwan applied for Data Analyst position',
    messageTh: 'กิตติพัฒน์ ลีสุวรรณ สมัครตำแหน่งนักวิเคราะห์ข้อมูล',
    type: 'INFO',
    read: false,
    actionUrl: '/dashboard/applications/app-006',
    createdAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'notif-002',
    userId: 'user-001',
    title: 'AI Recommendation Ready',
    titleTh: 'คำแนะนำ AI พร้อมแล้ว',
    message: 'AI has generated a hiring recommendation for Thanaporn Kittisak',
    messageTh: 'AI สร้างคำแนะนำการจ้างงานสำหรับ ธนพร กิตติศักดิ์ เสร็จแล้ว',
    type: 'ACTION_REQUIRED',
    read: false,
    actionUrl: '/dashboard/applications/app-001',
    createdAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'notif-003',
    userId: 'user-001',
    title: 'Interview Tomorrow',
    titleTh: 'สัมภาษณ์พรุ่งนี้',
    message: 'Phone screen with Arisa Suthawan at 11:00 AM',
    messageTh: 'สัมภาษณ์ทางโทรศัพท์กับ อริสา สุทธาวรรณ เวลา 11:00 น.',
    type: 'WARNING',
    read: true,
    actionUrl: '/dashboard/interviews',
    createdAt: '2026-08-18T08:00:00Z',
  },
  {
    id: 'notif-004',
    userId: 'user-001',
    title: 'JD Pending Approval',
    titleTh: 'JD รออนุมัติ',
    message: 'HR Business Partner job description is waiting for your approval',
    messageTh: 'Job Description ตำแหน่ง HR Business Partner รอการอนุมัติของคุณ',
    type: 'ACTION_REQUIRED',
    read: false,
    actionUrl: '/dashboard/vacancies/vac-003',
    createdAt: '2026-08-12T10:00:00Z',
  },
];

export const mockCurrentUser: User = {
  id: 'user-001',
  email: 'wanida.k@company.com',
  name: 'Wanida Kulrat',
  nameTh: 'วนิดา กุลรัตน์',
  role: 'HR_ADMIN',
  department: 'Human Resources',
  createdAt: '2026-01-01T09:00:00Z',
};
