// Mock Data — Applications with AI Screening & DL Test Results

import type { Application, AIScreeningResult, DLTestResult } from '@/lib/types/candidate';
import { mockCandidates } from './candidates';

const aiScreening1: AIScreeningResult = {
  matchScore: 88,
  confidence: 0.92,
  requiredCriteria: {
    education: 'match',
    experience: 'match',
    digital_marketing: 'match',
    leadership: 'match',
    analytics: 'match',
    english: 'partial',
  },
  strengths: [
    '6 years of direct digital marketing experience',
    'Master\'s degree in Digital Marketing from top university',
    'Currently in a lead role managing campaigns',
    'Strong CRM and analytics skills',
  ],
  gaps: [
    'English proficiency rated Advanced but not Native level',
    'No explicit higher education sector experience',
  ],
  evidence: [
    'Resume shows Google Ads, Meta Ads, SEO proficiency',
    'Led team of 4 at TechCorp Thailand',
    'Managed campaigns with 2M+ THB monthly budget',
  ],
  recommendation: 'SHORTLIST',
  generatedAt: '2026-08-06T10:30:00Z',
};

const aiScreening2: AIScreeningResult = {
  matchScore: 92,
  confidence: 0.95,
  requiredCriteria: {
    education: 'match',
    experience: 'match',
    typescript: 'match',
    react: 'match',
    cloud: 'match',
    system_design: 'match',
  },
  strengths: [
    '7 years software development experience',
    'Master\'s in Computer Science with high GPA',
    'Currently at Agoda — top tech company',
    'Full-stack proficiency with modern stack',
  ],
  gaps: [
    'Primary experience with web — limited mobile exposure',
  ],
  evidence: [
    'Resume confirms TypeScript, React, Node.js, AWS expertise',
    'Has contributed to open-source projects',
    'Designed microservices architecture at scale',
  ],
  recommendation: 'SHORTLIST',
  generatedAt: '2026-07-23T10:30:00Z',
};

const dlTestResult1: DLTestResult = {
  testId: 'dl-001',
  candidateId: 'cand-001',
  applicationId: 'app-001',
  knowledgeScore: 82,
  practicalScore: 76,
  aiLiteracyScore: 88,
  totalScore: 82,
  maxScore: 100,
  completedAt: '2026-08-12T15:30:00Z',
  resultStatus: 'PASS',
};

export const mockApplications: Application[] = [
  {
    id: 'app-001',
    candidateId: 'cand-001',
    candidate: mockCandidates[0],
    vacancyId: 'vac-001',
    vacancyTitle: 'Digital Marketing Manager',
    vacancyTitleTh: 'ผู้จัดการฝ่ายการตลาดดิจิทัล',
    department: 'Marketing',
    state: 'INTERVIEWED',
    aiScreeningResult: aiScreening1,
    matchScore: 88,
    interviewId: 'int-001',
    dlTestId: 'dl-001',
    dlTestResult: dlTestResult1,
    appliedAt: '2026-08-06T10:00:00Z',
    updatedAt: '2026-08-15T16:00:00Z',
  },
  {
    id: 'app-002',
    candidateId: 'cand-002',
    candidate: mockCandidates[1],
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    vacancyTitleTh: 'วิศวกรซอฟต์แวร์อาวุโส',
    department: 'Engineering',
    state: 'INTERVIEW_CONFIRMED',
    aiScreeningResult: aiScreening2,
    matchScore: 92,
    interviewId: 'int-002',
    appliedAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'app-003',
    candidateId: 'cand-003',
    candidate: mockCandidates[2],
    vacancyId: 'vac-001',
    vacancyTitle: 'Digital Marketing Manager',
    vacancyTitleTh: 'ผู้จัดการฝ่ายการตลาดดิจิทัล',
    department: 'Marketing',
    state: 'HR_REVIEW',
    matchScore: 68,
    aiScreeningResult: {
      matchScore: 68,
      confidence: 0.78,
      requiredCriteria: {
        education: 'match',
        experience: 'partial',
        digital_marketing: 'partial',
        leadership: 'no_match',
        analytics: 'partial',
        english: 'partial',
      },
      strengths: ['Good social media knowledge', 'Experience at LINE Thailand'],
      gaps: ['Only 4 years experience (requires 5+)', 'No management experience', 'Limited analytics depth'],
      evidence: ['Resume shows specialist-level role, not leadership'],
      recommendation: 'HOLD',
      generatedAt: '2026-08-08T11:00:00Z',
    },
    appliedAt: '2026-08-08T10:00:00Z',
    updatedAt: '2026-08-09T10:00:00Z',
  },
  {
    id: 'app-004',
    candidateId: 'cand-004',
    candidate: mockCandidates[3],
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    vacancyTitleTh: 'วิศวกรซอฟต์แวร์อาวุโส',
    department: 'Engineering',
    state: 'SHORTLISTED',
    matchScore: 79,
    aiScreeningResult: {
      matchScore: 79,
      confidence: 0.85,
      requiredCriteria: {
        education: 'match',
        experience: 'match',
        typescript: 'match',
        react: 'match',
        cloud: 'partial',
        system_design: 'partial',
      },
      strengths: ['5 years experience', 'React & TypeScript proficiency', 'Microservices background'],
      gaps: ['Limited cloud platform experience', 'No mentoring evidence'],
      evidence: ['Currently at Shopee — solid tech company', 'Working with React + TypeScript daily'],
      recommendation: 'SHORTLIST',
      generatedAt: '2026-07-29T10:00:00Z',
    },
    appliedAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'app-005',
    candidateId: 'cand-005',
    candidate: mockCandidates[4],
    vacancyId: 'vac-003',
    vacancyTitle: 'HR Business Partner',
    vacancyTitleTh: 'HR Business Partner',
    department: 'Human Resources',
    state: 'APPLIED',
    appliedAt: '2026-08-13T10:00:00Z',
    updatedAt: '2026-08-13T10:00:00Z',
  },
  {
    id: 'app-006',
    candidateId: 'cand-006',
    candidate: mockCandidates[5],
    vacancyId: 'vac-004',
    vacancyTitle: 'Data Analyst',
    vacancyTitleTh: 'นักวิเคราะห์ข้อมูล',
    department: 'Business Intelligence',
    state: 'AI_SCREENING',
    appliedAt: '2026-08-14T10:00:00Z',
    updatedAt: '2026-08-14T10:30:00Z',
  },
  {
    id: 'app-007',
    candidateId: 'cand-007',
    candidate: mockCandidates[6],
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    vacancyTitleTh: 'วิศวกรซอฟต์แวร์อาวุโส',
    department: 'Engineering',
    state: 'INTERVIEW_INVITED',
    matchScore: 85,
    aiScreeningResult: {
      matchScore: 85,
      confidence: 0.89,
      requiredCriteria: {
        education: 'match',
        experience: 'match',
        typescript: 'partial',
        react: 'partial',
        cloud: 'match',
        system_design: 'match',
      },
      strengths: ['6 years backend experience', 'System design expertise', 'AWS proficiency', 'Grab experience'],
      gaps: ['Primary Go/Python — TypeScript is secondary', 'React experience is limited'],
      evidence: ['Strong system design portfolio', 'Contributed to distributed systems at Grab'],
      recommendation: 'SHORTLIST',
      generatedAt: '2026-07-26T10:00:00Z',
    },
    appliedAt: '2026-07-25T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'app-008',
    candidateId: 'cand-008',
    candidate: mockCandidates[7],
    vacancyId: 'vac-001',
    vacancyTitle: 'Digital Marketing Manager',
    vacancyTitleTh: 'ผู้จัดการฝ่ายการตลาดดิจิทัล',
    department: 'Marketing',
    state: 'REJECTED',
    matchScore: 45,
    aiScreeningResult: {
      matchScore: 45,
      confidence: 0.82,
      requiredCriteria: {
        education: 'match',
        experience: 'no_match',
        digital_marketing: 'partial',
        leadership: 'no_match',
        analytics: 'no_match',
        english: 'partial',
      },
      strengths: ['Familiar with digital ads platforms'],
      gaps: ['Only 3 years experience (requires 5+)', 'No leadership experience', 'No analytics depth', 'Coordinator level, not manager'],
      evidence: ['Resume indicates execution-level role only'],
      recommendation: 'REJECT',
      generatedAt: '2026-08-10T11:00:00Z',
    },
    rejectionReason: 'Experience level does not meet minimum requirements for a Manager position',
    appliedAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-11T10:00:00Z',
  },
];
