// Mock Data — Candidates

import type { Candidate } from '@/lib/types/candidate';

export const mockCandidates: Candidate[] = [
  {
    id: 'cand-001',
    firstName: 'Thanaporn',
    lastName: 'Kittisak',
    firstNameTh: 'ธนพร',
    lastNameTh: 'กิตติศักดิ์',
    email: 'thanaporn.k@email.com',
    phone: '081-234-5678',
    currentPosition: 'Digital Marketing Lead',
    currentCompany: 'TechCorp Thailand',
    experienceYears: 6,
    education: [
      {
        degree: "Master's",
        field: 'Digital Marketing',
        institution: 'Chulalongkorn University',
        graduatedYear: 2020,
        gpa: 3.65,
      },
      {
        degree: "Bachelor's",
        field: 'Business Administration',
        institution: 'Thammasat University',
        graduatedYear: 2018,
        gpa: 3.42,
      },
    ],
    skills: ['Google Ads', 'Meta Ads', 'SEO', 'Analytics', 'CRM', 'Content Strategy', 'A/B Testing'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'ADVANCED' },
    ],
    source: 'CAREER_PORTAL',
    createdAt: '2026-08-06T10:00:00Z',
    updatedAt: '2026-08-06T10:00:00Z',
  },
  {
    id: 'cand-002',
    firstName: 'Pirasak',
    lastName: 'Wongcharoen',
    firstNameTh: 'พีรศักดิ์',
    lastNameTh: 'วงศ์เจริญ',
    email: 'pirasak.w@email.com',
    phone: '089-876-5432',
    currentPosition: 'Senior Full-Stack Developer',
    currentCompany: 'Agoda',
    experienceYears: 7,
    education: [
      {
        degree: "Master's",
        field: 'Computer Science',
        institution: 'KMUTT',
        graduatedYear: 2019,
        gpa: 3.78,
      },
    ],
    skills: ['TypeScript', 'React', 'Node.js', 'Python', 'AWS', 'PostgreSQL', 'Docker', 'Kubernetes'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'ADVANCED' },
      { name: 'Japanese', level: 'BASIC' },
    ],
    source: 'LINKEDIN',
    createdAt: '2026-07-22T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
  {
    id: 'cand-003',
    firstName: 'Narumon',
    lastName: 'Srisai',
    firstNameTh: 'นฤมล',
    lastNameTh: 'ศรีสาย',
    email: 'narumon.s@email.com',
    phone: '092-111-2233',
    currentPosition: 'Marketing Specialist',
    currentCompany: 'LINE Thailand',
    experienceYears: 4,
    education: [
      {
        degree: "Bachelor's",
        field: 'Communication Arts',
        institution: 'Chulalongkorn University',
        graduatedYear: 2022,
        gpa: 3.55,
      },
    ],
    skills: ['Social Media', 'Content Marketing', 'Google Ads', 'Canva', 'Copywriting'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'INTERMEDIATE' },
    ],
    source: 'EMAIL',
    createdAt: '2026-08-08T10:00:00Z',
    updatedAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'cand-004',
    firstName: 'Wichit',
    lastName: 'Chaicharoen',
    firstNameTh: 'วิชิต',
    lastNameTh: 'ชัยเจริญ',
    email: 'wichit.c@email.com',
    phone: '085-444-5566',
    currentPosition: 'Software Engineer',
    currentCompany: 'Shopee Thailand',
    experienceYears: 5,
    education: [
      {
        degree: "Bachelor's",
        field: 'Computer Engineering',
        institution: 'Kasetsart University',
        graduatedYear: 2021,
        gpa: 3.30,
      },
    ],
    skills: ['Java', 'Spring Boot', 'React', 'TypeScript', 'MongoDB', 'Redis', 'Microservices'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'ADVANCED' },
    ],
    source: 'CANDIDATE_POOL',
    createdAt: '2026-07-28T10:00:00Z',
    updatedAt: '2026-08-05T10:00:00Z',
  },
  {
    id: 'cand-005',
    firstName: 'Supansa',
    lastName: 'Tangkeo',
    firstNameTh: 'สุพรรษา',
    lastNameTh: 'ตั้งแก้ว',
    email: 'supansa.t@email.com',
    phone: '063-999-8877',
    currentPosition: 'HR Manager',
    currentCompany: 'SCB',
    experienceYears: 8,
    education: [
      {
        degree: "Master's",
        field: 'Human Resource Management',
        institution: 'NIDA',
        graduatedYear: 2018,
        gpa: 3.82,
      },
    ],
    skills: ['HRBP', 'Labor Law', 'Talent Acquisition', 'Performance Management', 'OD', 'Compensation & Benefits'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'ADVANCED' },
    ],
    source: 'REFERRAL',
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'cand-006',
    firstName: 'Kittipat',
    lastName: 'Leesuwan',
    firstNameTh: 'กิตติพัฒน์',
    lastNameTh: 'ลีสุวรรณ',
    email: 'kittipat.l@email.com',
    phone: '091-222-3344',
    currentPosition: 'Data Analyst',
    currentCompany: 'True Digital',
    experienceYears: 3,
    education: [
      {
        degree: "Bachelor's",
        field: 'Statistics',
        institution: 'Mahidol University',
        graduatedYear: 2023,
        gpa: 3.48,
      },
    ],
    skills: ['SQL', 'Python', 'Tableau', 'Power BI', 'Excel', 'R', 'Data Modeling'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'INTERMEDIATE' },
    ],
    source: 'CAREER_PORTAL',
    createdAt: '2026-08-14T10:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'cand-007',
    firstName: 'Arisa',
    lastName: 'Suthawan',
    firstNameTh: 'อริสา',
    lastNameTh: 'สุทธาวรรณ',
    email: 'arisa.s@email.com',
    phone: '088-555-6677',
    currentPosition: 'Backend Developer',
    currentCompany: 'Grab Thailand',
    experienceYears: 6,
    education: [
      {
        degree: "Master's",
        field: 'Software Engineering',
        institution: 'Chiang Mai University',
        graduatedYear: 2020,
        gpa: 3.71,
      },
    ],
    skills: ['Go', 'Python', 'gRPC', 'Kafka', 'PostgreSQL', 'Docker', 'AWS', 'System Design'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'ADVANCED' },
    ],
    source: 'LINKEDIN',
    createdAt: '2026-07-25T10:00:00Z',
    updatedAt: '2026-08-08T10:00:00Z',
  },
  {
    id: 'cand-008',
    firstName: 'Patcharee',
    lastName: 'Manoon',
    firstNameTh: 'พัชรี',
    lastNameTh: 'มานูญ',
    email: 'patcharee.m@email.com',
    phone: '064-777-8899',
    currentPosition: 'Digital Marketing Coordinator',
    currentCompany: 'AIS',
    experienceYears: 3,
    education: [
      {
        degree: "Bachelor's",
        field: 'Marketing',
        institution: 'Bangkok University',
        graduatedYear: 2023,
        gpa: 3.20,
      },
    ],
    skills: ['Google Ads', 'Facebook Ads', 'Instagram', 'TikTok Ads', 'Analytics'],
    languages: [
      { name: 'Thai', level: 'NATIVE' },
      { name: 'English', level: 'INTERMEDIATE' },
    ],
    source: 'CAREER_PORTAL',
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
];
