// Mock Data — Interviews

import type { Interview } from '@/lib/types/interview';

export const mockInterviews: Interview[] = [
  {
    id: 'int-001',
    applicationId: 'app-001',
    candidateId: 'cand-001',
    candidateName: 'Thanaporn Kittisak',
    candidateNameTh: 'ธนพร กิตติศักดิ์',
    vacancyId: 'vac-001',
    vacancyTitle: 'Digital Marketing Manager',
    type: 'PANEL',
    status: 'COMPLETED',
    scheduledAt: '2026-08-14T10:00:00Z',
    duration: 60,
    location: 'Meeting Room A, 5th Floor',
    interviewers: [
      { id: 'user-002', name: 'Somchai Prasert', role: 'VP Marketing', department: 'Marketing' },
      { id: 'user-005', name: 'Wanida Kulrat', role: 'HR Manager', department: 'Human Resources' },
    ],
    feedback: [
      {
        interviewerId: 'user-002',
        interviewerName: 'Somchai Prasert',
        scores: { technicalSkill: 85, communication: 90, problemSolving: 82, teamwork: 88, cultureFit: 85 },
        overallScore: 86,
        strengths: ['Strong digital marketing knowledge', 'Clear communication and presentation skills', 'Good leadership examples'],
        concerns: ['Limited experience in higher education sector'],
        recommendation: 'HIRE',
        submittedAt: '2026-08-14T12:00:00Z',
      },
      {
        interviewerId: 'user-005',
        interviewerName: 'Wanida Kulrat',
        scores: { technicalSkill: 80, communication: 88, problemSolving: 78, teamwork: 90, cultureFit: 92 },
        overallScore: 85,
        strengths: ['Excellent cultural fit', 'Team-oriented approach', 'Growth mindset'],
        concerns: ['Salary expectation may be above range'],
        recommendation: 'HIRE',
        submittedAt: '2026-08-14T13:00:00Z',
      },
    ],
    overallScore: 86,
    createdAt: '2026-08-10T10:00:00Z',
    updatedAt: '2026-08-14T13:00:00Z',
  },
  {
    id: 'int-002',
    applicationId: 'app-002',
    candidateId: 'cand-002',
    candidateName: 'Pirasak Wongcharoen',
    candidateNameTh: 'พีรศักดิ์ วงศ์เจริญ',
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    type: 'TECHNICAL',
    status: 'CONFIRMED',
    scheduledAt: '2026-08-20T14:00:00Z',
    duration: 90,
    meetingUrl: 'https://meet.google.com/abc-defg-hij',
    interviewers: [
      { id: 'user-003', name: 'Nattapong Sriwan', role: 'Engineering Manager', department: 'Engineering' },
      { id: 'user-006', name: 'Prakit Tangsri', role: 'Tech Lead', department: 'Engineering' },
    ],
    createdAt: '2026-08-12T10:00:00Z',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'int-003',
    applicationId: 'app-007',
    candidateId: 'cand-007',
    candidateName: 'Arisa Suthawan',
    candidateNameTh: 'อริสา สุทธาวรรณ',
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    type: 'PHONE_SCREEN',
    status: 'SCHEDULED',
    scheduledAt: '2026-08-19T11:00:00Z',
    duration: 30,
    meetingUrl: 'https://meet.google.com/xyz-uvwx-yz',
    interviewers: [
      { id: 'user-005', name: 'Wanida Kulrat', role: 'HR Manager', department: 'Human Resources' },
    ],
    createdAt: '2026-08-15T10:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'int-004',
    applicationId: 'app-004',
    candidateId: 'cand-004',
    candidateName: 'Wichit Chaicharoen',
    candidateNameTh: 'วิชิต ชัยเจริญ',
    vacancyId: 'vac-002',
    vacancyTitle: 'Senior Software Engineer',
    type: 'TECHNICAL',
    status: 'SCHEDULED',
    scheduledAt: '2026-08-21T10:00:00Z',
    duration: 90,
    location: 'Meeting Room B, 3rd Floor',
    interviewers: [
      { id: 'user-003', name: 'Nattapong Sriwan', role: 'Engineering Manager', department: 'Engineering' },
    ],
    createdAt: '2026-08-16T10:00:00Z',
    updatedAt: '2026-08-16T10:00:00Z',
  },
];
