// Mock Data — Vacancies, Positions, Job Descriptions

import type { Vacancy, Position, JobDescription } from '@/lib/types/vacancy';

export const mockPositions: Position[] = [
  {
    id: 'pos-001',
    title: 'Digital Marketing Manager',
    titleTh: 'ผู้จัดการฝ่ายการตลาดดิจิทัล',
    department: 'Marketing',
    departmentTh: 'การตลาด',
    level: 'Manager',
    reportTo: 'VP Marketing',
    responsibilities: [
      'Develop and execute digital marketing strategies',
      'Manage online advertising campaigns (Google Ads, Meta Ads)',
      'Analyze marketing performance data and optimize ROI',
      'Lead a team of 5 digital marketing specialists',
      'Collaborate with product and sales teams on go-to-market strategies',
    ],
    responsibilitiesTh: [
      'พัฒนาและดำเนินกลยุทธ์การตลาดดิจิทัล',
      'จัดการแคมเปญโฆษณาออนไลน์ (Google Ads, Meta Ads)',
      'วิเคราะห์ข้อมูลผลการตลาดและเพิ่มประสิทธิภาพ ROI',
      'นำทีมผู้เชี่ยวชาญการตลาดดิจิทัล 5 คน',
      'ร่วมมือกับทีมผลิตภัณฑ์และฝ่ายขายในกลยุทธ์ Go-to-market',
    ],
    qualifications: [
      "Bachelor's degree in Marketing, Business, or related field",
      '5+ years of digital marketing experience',
      'Experience with analytics tools (Google Analytics, Data Studio)',
      'Strong leadership and communication skills',
    ],
    qualificationsTh: [
      'ปริญญาตรีสาขาการตลาด บริหารธุรกิจ หรือสาขาที่เกี่ยวข้อง',
      'ประสบการณ์ด้านการตลาดดิจิทัล 5 ปีขึ้นไป',
      'มีประสบการณ์กับเครื่องมือวิเคราะห์ (Google Analytics, Data Studio)',
      'มีทักษะความเป็นผู้นำและการสื่อสารที่แข็งแกร่ง',
    ],
    createdAt: '2026-07-01T09:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'pos-002',
    title: 'Senior Software Engineer',
    titleTh: 'วิศวกรซอฟต์แวร์อาวุโส',
    department: 'Engineering',
    departmentTh: 'วิศวกรรม',
    level: 'Senior',
    reportTo: 'Engineering Manager',
    responsibilities: [
      'Design and develop scalable web applications',
      'Code review and mentoring junior developers',
      'Architect technical solutions for complex problems',
      'Collaborate with product managers on feature planning',
      'Maintain CI/CD pipelines and infrastructure',
    ],
    responsibilitiesTh: [
      'ออกแบบและพัฒนาเว็บแอปพลิเคชันที่รองรับการขยายตัว',
      'ตรวจสอบโค้ดและให้คำแนะนำนักพัฒนารุ่นใหม่',
      'ออกแบบสถาปัตยกรรมโซลูชันเทคนิคสำหรับปัญหาที่ซับซ้อน',
      'ร่วมมือกับผู้จัดการผลิตภัณฑ์ในการวางแผนฟีเจอร์',
      'ดูแล CI/CD Pipeline และโครงสร้างพื้นฐาน',
    ],
    qualifications: [
      "Bachelor's or Master's in Computer Science",
      '5+ years of software development experience',
      'Proficiency in TypeScript, React, Node.js',
      'Experience with cloud platforms (AWS/GCP/Azure)',
      'Strong problem-solving skills',
    ],
    qualificationsTh: [
      'ปริญญาตรีหรือโทสาขาวิทยาการคอมพิวเตอร์',
      'ประสบการณ์พัฒนาซอฟต์แวร์ 5 ปีขึ้นไป',
      'เชี่ยวชาญ TypeScript, React, Node.js',
      'มีประสบการณ์กับแพลตฟอร์มคลาวด์ (AWS/GCP/Azure)',
      'มีทักษะการแก้ปัญหาที่แข็งแกร่ง',
    ],
    createdAt: '2026-06-15T09:00:00Z',
    updatedAt: '2026-07-20T10:00:00Z',
  },
  {
    id: 'pos-003',
    title: 'HR Business Partner',
    titleTh: 'HR Business Partner',
    department: 'Human Resources',
    departmentTh: 'ทรัพยากรบุคคล',
    level: 'Senior',
    reportTo: 'HR Director',
    responsibilities: [
      'Partner with business leaders to align HR strategies',
      'Drive talent acquisition and retention initiatives',
      'Manage employee relations and performance management',
      'Develop and implement HR policies',
      'Support organizational development and change management',
    ],
    responsibilitiesTh: [
      'ร่วมงานกับผู้บริหารเพื่อวางแผนกลยุทธ์ HR',
      'ขับเคลื่อนแผนการสรรหาและรักษาบุคลากร',
      'จัดการแรงงานสัมพันธ์และการบริหารผลงาน',
      'พัฒนาและดำเนินนโยบาย HR',
      'สนับสนุนการพัฒนาองค์กรและการจัดการการเปลี่ยนแปลง',
    ],
    qualifications: [
      "Bachelor's degree in HR, Psychology, or Business",
      '7+ years of HR experience',
      'Strong knowledge of Thai labor law',
      'HRBP certification preferred',
      'Excellent interpersonal and negotiation skills',
    ],
    qualificationsTh: [
      'ปริญญาตรีสาขา HR จิตวิทยา หรือบริหารธุรกิจ',
      'ประสบการณ์ด้าน HR 7 ปีขึ้นไป',
      'มีความรู้กฎหมายแรงงานไทยอย่างดี',
      'มี HRBP certification จะพิจารณาเป็นพิเศษ',
      'มีทักษะมนุษยสัมพันธ์และการเจรจาต่อรองที่ยอดเยี่ยม',
    ],
    createdAt: '2026-07-10T09:00:00Z',
    updatedAt: '2026-07-25T10:00:00Z',
  },
  {
    id: 'pos-004',
    title: 'Data Analyst',
    titleTh: 'นักวิเคราะห์ข้อมูล',
    department: 'Business Intelligence',
    departmentTh: 'ธุรกิจอัจฉริยะ',
    level: 'Mid-Level',
    reportTo: 'BI Manager',
    responsibilities: [
      'Collect, clean, and analyze business data',
      'Create dashboards and reports using BI tools',
      'Identify trends and provide actionable insights',
      'Collaborate with stakeholders on data requirements',
      'Maintain data quality and documentation',
    ],
    responsibilitiesTh: [
      'รวบรวม ทำความสะอาด และวิเคราะห์ข้อมูลธุรกิจ',
      'สร้างแดชบอร์ดและรายงานโดยใช้เครื่องมือ BI',
      'ระบุแนวโน้มและให้ข้อมูลเชิงลึกที่นำไปใช้ได้',
      'ร่วมมือกับผู้มีส่วนได้เสียเกี่ยวกับความต้องการข้อมูล',
      'ดูแลคุณภาพข้อมูลและเอกสาร',
    ],
    qualifications: [
      "Bachelor's degree in Statistics, Math, CS, or related field",
      '3+ years of data analysis experience',
      'Proficiency in SQL, Python, and BI tools',
      'Strong analytical and visualization skills',
    ],
    qualificationsTh: [
      'ปริญญาตรีสาขาสถิติ คณิตศาสตร์ วิทยาการคอมพิวเตอร์ หรือสาขาที่เกี่ยวข้อง',
      'ประสบการณ์วิเคราะห์ข้อมูล 3 ปีขึ้นไป',
      'เชี่ยวชาญ SQL, Python และเครื่องมือ BI',
      'มีทักษะการวิเคราะห์และการสร้าง Visualization ที่ดี',
    ],
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-10T10:00:00Z',
  },
];

export const mockJobDescriptions: JobDescription[] = [
  {
    id: 'jd-001',
    vacancyId: 'vac-001',
    version: 2,
    jobTitle: 'Digital Marketing Manager',
    jobTitleTh: 'ผู้จัดการฝ่ายการตลาดดิจิทัล',
    summary: 'We are looking for an experienced Digital Marketing Manager to lead our online marketing efforts and drive measurable growth.',
    summaryTh: 'เรากำลังมองหาผู้จัดการฝ่ายการตลาดดิจิทัลที่มีประสบการณ์ เพื่อนำการตลาดออนไลน์และขับเคลื่อนการเติบโตที่วัดผลได้',
    responsibilities: [
      'Develop comprehensive digital marketing strategies aligned with business goals',
      'Manage and optimize paid advertising campaigns across multiple platforms',
      'Lead SEO/SEM initiatives to increase organic traffic',
      'Oversee social media strategy and content calendar',
      'Analyze campaign performance and present insights to leadership',
    ],
    responsibilitiesTh: [
      'พัฒนากลยุทธ์การตลาดดิจิทัลที่ครอบคลุมและสอดคล้องกับเป้าหมายธุรกิจ',
      'จัดการและเพิ่มประสิทธิภาพแคมเปญโฆษณาข้ามแพลตฟอร์ม',
      'นำ SEO/SEM เพื่อเพิ่ม Organic Traffic',
      'ดูแลกลยุทธ์โซเชียลมีเดียและปฏิทินคอนเทนต์',
      'วิเคราะห์ประสิทธิภาพแคมเปญและนำเสนอข้อมูลเชิงลึกต่อผู้บริหาร',
    ],
    requirements: [
      "Bachelor's degree in Marketing or related field",
      '5+ years of digital marketing experience',
      'Proven track record of managing campaigns with $100K+ budgets',
      'Expertise in Google Ads, Meta Ads, and analytics platforms',
      'Strong leadership and team management skills',
    ],
    requirementsTh: [
      'ปริญญาตรีสาขาการตลาดหรือสาขาที่เกี่ยวข้อง',
      'ประสบการณ์การตลาดดิจิทัล 5 ปีขึ้นไป',
      'มีผลงานจัดการแคมเปญงบประมาณ $100K+',
      'เชี่ยวชาญ Google Ads, Meta Ads และแพลตฟอร์มวิเคราะห์',
      'ทักษะความเป็นผู้นำและการจัดการทีมที่แข็งแกร่ง',
    ],
    preferredSkills: ['Marketing Automation', 'A/B Testing', 'CRM (HubSpot/Salesforce)', 'Data Visualization'],
    education: ["Bachelor's in Marketing, Communications, or Business"],
    experience: ['5+ years in digital marketing', '2+ years in management role'],
    benefits: ['Hybrid work arrangement', 'Annual learning budget $2,000', 'Health & dental insurance', 'Performance bonus'],
    benefitsTh: ['ทำงานแบบ Hybrid', 'งบเรียนรู้ประจำปี $2,000', 'ประกันสุขภาพและทันตกรรม', 'โบนัสผลงาน'],
    salaryRange: { min: 60000, max: 90000, currency: 'THB' },
    generatedByAI: true,
    approvedBy: 'hr-001',
    approvedAt: '2026-08-05T14:30:00Z',
    createdAt: '2026-08-03T10:00:00Z',
  },
];

export const mockVacancies: Vacancy[] = [
  {
    id: 'vac-001',
    positionId: 'pos-001',
    position: mockPositions[0],
    jobDescription: mockJobDescriptions[0],
    state: 'RECRUITING',
    priority: 'HIGH',
    headcount: 1,
    filled: 0,
    openDate: '2026-08-05',
    reason: 'REPLACEMENT',
    reasonDetail: 'Previous manager resigned',
    hiringManagerId: 'user-002',
    hiringManagerName: 'Somchai Prasert',
    applicationCount: 12,
    shortlistedCount: 4,
    interviewCount: 2,
    createdAt: '2026-08-01T09:00:00Z',
    updatedAt: '2026-08-15T10:00:00Z',
  },
  {
    id: 'vac-002',
    positionId: 'pos-002',
    position: mockPositions[1],
    state: 'INTERVIEWING',
    priority: 'URGENT',
    headcount: 2,
    filled: 0,
    openDate: '2026-07-20',
    reason: 'EXPANSION',
    reasonDetail: 'New product team needs senior engineers',
    hiringManagerId: 'user-003',
    hiringManagerName: 'Nattapong Sriwan',
    applicationCount: 28,
    shortlistedCount: 8,
    interviewCount: 5,
    createdAt: '2026-07-15T09:00:00Z',
    updatedAt: '2026-08-16T10:00:00Z',
  },
  {
    id: 'vac-003',
    positionId: 'pos-003',
    position: mockPositions[2],
    state: 'WAITING_HR_APPROVAL',
    priority: 'MEDIUM',
    headcount: 1,
    filled: 0,
    openDate: '2026-08-10',
    reason: 'NEW_POSITION',
    hiringManagerId: 'user-004',
    hiringManagerName: 'Pranee Suksawat',
    applicationCount: 0,
    shortlistedCount: 0,
    interviewCount: 0,
    createdAt: '2026-08-08T09:00:00Z',
    updatedAt: '2026-08-12T10:00:00Z',
  },
  {
    id: 'vac-004',
    positionId: 'pos-004',
    position: mockPositions[3],
    state: 'PUBLISHED',
    priority: 'LOW',
    headcount: 1,
    filled: 0,
    openDate: '2026-08-12',
    reason: 'REPLACEMENT',
    hiringManagerId: 'user-002',
    hiringManagerName: 'Somchai Prasert',
    applicationCount: 6,
    shortlistedCount: 2,
    interviewCount: 0,
    createdAt: '2026-08-10T09:00:00Z',
    updatedAt: '2026-08-14T10:00:00Z',
  },
  {
    id: 'vac-005',
    positionId: 'pos-001',
    position: mockPositions[0],
    state: 'DRAFT',
    priority: 'MEDIUM',
    headcount: 1,
    filled: 0,
    openDate: '2026-08-18',
    reason: 'EXPANSION',
    hiringManagerId: 'user-002',
    hiringManagerName: 'Somchai Prasert',
    applicationCount: 0,
    shortlistedCount: 0,
    interviewCount: 0,
    createdAt: '2026-08-16T09:00:00Z',
    updatedAt: '2026-08-16T09:00:00Z',
  },
  {
    id: 'vac-006',
    positionId: 'pos-002',
    position: mockPositions[1],
    state: 'FILLED',
    priority: 'HIGH',
    headcount: 1,
    filled: 1,
    openDate: '2026-06-01',
    closeDate: '2026-07-15',
    reason: 'REPLACEMENT',
    hiringManagerId: 'user-003',
    hiringManagerName: 'Nattapong Sriwan',
    applicationCount: 15,
    shortlistedCount: 5,
    interviewCount: 3,
    createdAt: '2026-05-20T09:00:00Z',
    updatedAt: '2026-07-15T10:00:00Z',
  },
];
