-- Migration: JD 8 หมวดมาตรฐาน (SPU JD Architect Full Pipeline)
-- อ้างอิง: document/implementation_plan for develop function ai training.md — Component 1
-- หมายเหตุ: สคริปต์นี้ใช้ IF NOT EXISTS ทุกจุด รันซ้ำได้อย่างปลอดภัย (idempotent)
-- สถานะ: รันบน Supabase production/dev database เรียบร้อยแล้ว (เก็บไว้เพื่อ sync กับ
--        environment อื่น เช่น local/staging ที่ยังไม่ได้รัน)

-- ==========================================
-- 1. เพิ่มฟิลด์ 8 หมวดมาตรฐานในตาราง job_descriptions
-- ==========================================
ALTER TABLE job_descriptions
  -- หมวด 1: ข้อมูลตำแหน่งเพิ่มเติม (Position Identification)
  ADD COLUMN IF NOT EXISTS unit_group VARCHAR(200),
  ADD COLUMN IF NOT EXISTS unit_name VARCHAR(200),
  ADD COLUMN IF NOT EXISTS track VARCHAR(100),
  ADD COLUMN IF NOT EXISTS position_level VARCHAR(100),
  ADD COLUMN IF NOT EXISTS reports_to VARCHAR(200),
  ADD COLUMN IF NOT EXISTS subordinates JSONB DEFAULT '[]',
  ADD COLUMN IF NOT EXISTS unit_profile VARCHAR(10),

  -- หมวด 2: วัตถุประสงค์ของตำแหน่ง (Job Purpose)
  ADD COLUMN IF NOT EXISTS job_purpose TEXT,
  ADD COLUMN IF NOT EXISTS job_purpose_th TEXT,

  -- หมวด 3: หน้าที่ความรับผิดชอบหลัก (Key Responsibilities) — โครงสร้างใหม่แบ่งกลุ่ม
  ADD COLUMN IF NOT EXISTS responsibilities_grouped JSONB DEFAULT '[]',

  -- หมวด 4: ตัวชี้วัดผลงาน (KPIs)
  ADD COLUMN IF NOT EXISTS kpis JSONB DEFAULT '[]',

  -- หมวด 6: สมรรถนะ (Competencies)
  ADD COLUMN IF NOT EXISTS competencies JSONB DEFAULT '{}',

  -- หมวด 7: ความสัมพันธ์ในการทำงาน (Working Relationships)
  ADD COLUMN IF NOT EXISTS working_relationships JSONB DEFAULT '{}',

  -- หมวด 8: เงื่อนไขและความเสี่ยง (Working Conditions & Risk)
  ADD COLUMN IF NOT EXISTS working_conditions JSONB DEFAULT '{}',

  -- Metadata เพิ่มเติม
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) DEFAULT 'DRAFT',
  ADD COLUMN IF NOT EXISTS tags TEXT[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS prompt_used TEXT,
  ADD COLUMN IF NOT EXISTS is_benchmark BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS review_flags JSONB DEFAULT '[]';

-- ==========================================
-- 2. ตาราง job_training_profiles (สำหรับหน้า "เทรนโมเดล AI")
-- ==========================================
CREATE TABLE IF NOT EXISTS job_training_profiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  position_id BIGINT REFERENCES positions(id) UNIQUE,
  position_title VARCHAR(200) NOT NULL,
  position_title_th VARCHAR(200),
  department VARCHAR(100) NOT NULL,
  level VARCHAR(50),
  education_level VARCHAR(100),
  min_experience_years INTEGER DEFAULT 0,
  standard_responsibilities JSONB DEFAULT '[]',
  required_skills JSONB DEFAULT '[]',
  ai_guidelines TEXT,
  standard_benefits JSONB DEFAULT '[]',
  salary_range JSONB DEFAULT '{"min": 0, "max": 0}',
  unit_profile VARCHAR(10),          -- P1-P7
  track VARCHAR(100),                -- สายงาน
  is_trained BOOLEAN DEFAULT FALSE,
  last_trained_at TIMESTAMPTZ,
  updated_by BIGINT REFERENCES users(id),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ==========================================
-- 3. [FUTURE] ตารางสำหรับคณะ/วิทยาลัย (ยังไม่สร้าง — เตรียมไว้สำหรับอนาคต)
-- ==========================================
-- CREATE TABLE IF NOT EXISTS faculties (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   name VARCHAR(200) NOT NULL,
--   name_th VARCHAR(200),
--   code VARCHAR(20) UNIQUE,
--   is_active BOOLEAN DEFAULT TRUE,
--   created_at TIMESTAMPTZ DEFAULT NOW()
-- );
