-- =========================================================================
-- HR AI Agent — Notifications System Setup Script
-- คำแนะนำ: คัดลอกสคริปต์นี้ไปวางและกด Run ใน Supabase SQL Editor
-- =========================================================================

-- 1. สร้างตาราง notifications (ถ้ายังไม่มี)
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) DEFAULT 1,
  title VARCHAR(255) NOT NULL,
  title_th VARCHAR(255),
  message TEXT NOT NULL,
  message_th TEXT,
  type VARCHAR(20) DEFAULT 'INFO', -- INFO, SUCCESS, WARNING, ACTION_REQUIRED
  is_read BOOLEAN DEFAULT FALSE,
  action_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. สร้าง Index เพื่อเพิ่มความเร็วในการดึงการแจ้งเตือน
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, is_read);
CREATE INDEX IF NOT EXISTS idx_notifications_created ON notifications(created_at DESC);

-- 3. เพิ่มข้อมูลการแจ้งเตือนเริ่มต้นสำหรับทดสอบระบบ
INSERT INTO notifications (user_id, title, title_th, message, message_th, type, is_read, action_url)
VALUES
  (
    1, 
    'New Application Received', 
    '📄 มีใบสมัครงานใหม่', 
    'Kittipat Leesuwann applied for Data Scientist position', 
    'กิตติพัฒน์ ลีสุวรรณ สมัครตำแหน่ง Data Scientist พร้อมแนบเรซูเม่', 
    'INFO', 
    false, 
    '/dashboard/applications'
  ),
  (
    1, 
    'AI Candidate Screening Ready', 
    '🤖 ผลการคัดกรอง AI พร้อมแล้ว', 
    'Google Gemini completed evaluation for Thanaporn Kittisak (Match Score: 94%)', 
    'AI (Gemini) วิเคราะห์คำแนะนำการจ้างงานสำหรับ ธนพร กิตติศักดิ์ (คะแนน 94%) เสร็จสิ้นแล้ว', 
    'SUCCESS', 
    false, 
    '/dashboard/applications'
  ),
  (
    1, 
    'Interview Schedule Alert', 
    '📅 มีการนัดหมายสัมภาษณ์', 
    'Interview with Arisa Sutthawann is scheduled for today at 14:00', 
    'นัดสัมภาษณ์ออนไลน์กับ อริสา สุทธาวรรณ วันนี้เวลา 14:00 น.', 
    'ACTION_REQUIRED', 
    false, 
    '/dashboard/interviews'
  ),
  (
    1, 
    'AI Job Description Ready for Approval', 
    '📝 JD ร่างเสร็จแล้ว - รออนุมัติ', 
    'Job Description for Senior AI Engineer generated by Gemini is waiting for HR approval', 
    'Job Description ตำแหน่ง Senior AI Engineer ร่างโดย Gemini พร้อมให้ HR ตรวจสอบและอนุมัติ', 
    'INFO', 
    false, 
    '/dashboard/ai-agent'
  )
ON CONFLICT DO NOTHING;

-- 4. ตรวจสอบข้อมูลการแจ้งเตือน
SELECT id, title_th, message_th, type, is_read, action_url, created_at FROM notifications ORDER BY created_at DESC;
